<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	 xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	 xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	 xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" name="macroed">

	
	<gazebo>  
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>   
      <leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
      <rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
      <leftRearJoint>left_back_wheel_joint</leftRearJoint>
      <rightRearJoint>right_back_wheel_joint</rightRearJoint>
      <wheelSeparation>0.4</wheelSeparation>
      <wheelDiameter>0.07</wheelDiameter>   
      <torque>10</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
	  <odometrySource>map</odometrySource>
	  <publishOdomTF>true</publishOdomTF>
      <robotBaseFrame>base_footprint</robotBaseFrame>
	  <publishWheelTF>false</publishWheelTF>
      <publishTf>true</publishTf>
	  <publishWheelJointState>true</publishWheelJointState>

  </plugin>
  </gazebo>

   <!-- Ground Truth Pose -->
    <gazebo>
        <plugin name="gazebo_ros_p3d" filename="libgazebo_ros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>30.0</updateRate>
        <bodyName>base_footprint</bodyName>
        <topicName>ground_truth_pose</topicName>
        <gaussianNoise>0.0</gaussianNoise>
        <frameName>map</frameName>
        </plugin>
    </gazebo>  

	
	<xacro:property name="width" value=".2" />
	<xacro:property name="leglen" value=".6" />
	<xacro:property name="polelen" value=".2" />
	<xacro:property name="bodylen" value=".6" />
	<xacro:property name="baselen" value=".4" />
	<xacro:property name="wheeldiam" value=".07" />
	<xacro:property name="pi" value="3.1415" />



	<xacro:macro name="default_inertial" params="mass">
		<inertial>
      			<mass value="${mass}" />
		        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
			         iyy="1.0" iyz="0.0"
			         izz="1.0" />
		</inertial>
	</xacro:macro>

	<link name="base_link">
		<visual>
			<geometry>
				<cylinder radius="${width}" length="${bodylen}"/>
			</geometry>
			<material name="blue">
				<color rgba="0 0 .8 1"/>
			</material>
		</visual>
		<collision>
			<geometry>
				<cylinder radius="${width}" length="${bodylen}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="10"/>
	</link>

	<link name="base_footprint">
		<visual>
		<geometry>
			<box size="0.001 0.001 0.001"/>
		</geometry>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		</visual>
		<inertial>
		<mass value="0.0001"/>
		<inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
		</inertial>	
	</link>
	
	<gazebo reference="base_footprint">
    	<material>Gazebo/Blue</material>
	</gazebo>

	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0" />
		<parent link="base_footprint" />
		<child link="base_link" />
	</joint>


	<xacro:macro name="wheel" params="prefix suffix reflect">
		<link name="${prefix}_${suffix}_wheel">
			<visual>
				<geometry>
					<cylinder radius="${wheeldiam/2}" length=".1"/>
				</geometry>
				<material name="black">
					<color rgba="0 0 0 1"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<cylinder radius="${wheeldiam/2}" length=".1"/>
				</geometry>
			</collision>
			<xacro:default_inertial mass="1"/>
		</link>
		<joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
			<axis xyz="0 0 1"/>
			<parent link="${prefix}_base"/>
			<child link="${prefix}_${suffix}_wheel"/>
			<origin xyz="0 ${baselen*reflect/3} -${wheeldiam/2+.05}" rpy="0 ${pi/2} 0"/>
      			<limit effort="100" velocity="100" />
			<dynamics damping="0.0" friction="0.0" />

		</joint>

	</xacro:macro>

 

	<xacro:macro name="leg" params="prefix reflect">
		<link name="${prefix}_leg">
			<visual>
				<geometry>
					<box size="${leglen} .2 .1"/>
				</geometry>
				<origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
				<material name="white">
					<color rgba="1 1 1 1"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<box size="${leglen} .2 .1"/>
				</geometry>
				<origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/>
			</collision>
			<xacro:default_inertial mass="10"/>
		</link>

		<joint name="base_to_${prefix}_leg" type="fixed">
			<parent link="base_link"/>
			<child link="${prefix}_leg"/>
			<origin xyz="${reflect*(width+.02)} 0 .25" />
		</joint>

		<link name="${prefix}_base">
			<visual>
				<geometry>
					<box size=".1 ${baselen} .1"/>
				</geometry>
				<material name="white"/>
			</visual>
			<collision>
				<geometry>
					<box size=".1 ${baselen} .1"/>
				</geometry>
			</collision>
			<xacro:default_inertial mass="10"/>
		</link>

		<joint name="${prefix}_base_joint" type="fixed">
			<parent link="${prefix}_leg"/>
			<child link="${prefix}_base"/>
			<origin xyz="0 0 ${-leglen}" />
		</joint>
		<xacro:wheel prefix="${prefix}" suffix="front" reflect="1"/>
		<xacro:wheel prefix="${prefix}" suffix="back" reflect="-1"/>
	</xacro:macro>
	<xacro:leg prefix="right" reflect="1" />
	<xacro:leg prefix="left" reflect="-1" />

	<joint name="gripper_extension" type="prismatic">
		<parent link="base_link"/>
		<child link="gripper_pole"/>
    		<limit effort="1000.0" lower="-${width*2-.02}" upper="0" velocity="0.5"/>
		<origin rpy="0 0 ${pi/2}" xyz="0 ${width-.01} .2"/>
	</joint>

	<link name="gripper_pole">
		<visual>
			<geometry>
				<cylinder length="${polelen}" radius=".01"/>
			</geometry>
			<origin xyz="${polelen/2} 0 0" rpy="0 ${pi/2} 0 "/>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${polelen}" radius=".01"/>
			</geometry>
			<origin xyz="${polelen/2} 0 0" rpy="0 ${pi/2} 0 "/>
		</collision>
		<xacro:default_inertial mass=".05"/>
	</link>
	
	<xacro:macro name="gripper" params="prefix reflect">
		<joint name="${prefix}_gripper_joint" type="revolute">
			<axis xyz="0 0 ${reflect}"/>
			<limit effort="1000.0" lower="0.0" upper="0.548" velocity="0.5"/>
			<origin rpy="0 0 0" xyz="${polelen} ${reflect*0.01} 0"/>
			<parent link="gripper_pole"/>
			<child link="${prefix}_gripper"/>
		</joint>
		<link name="${prefix}_gripper">
			<visual>
     				<origin rpy="${(reflect-1)/2*pi} 0 0" xyz="0 0 0"/>
				<geometry>
					<mesh filename="package://pr2_description/meshes/gripper_v0/l_finger.dae"/>
				</geometry>
			</visual>
			<collision>
				<geometry>
					<mesh filename="package://pr2_description/meshes/gripper_v0/l_finger.dae"/>
				</geometry>
     				<origin rpy="${(reflect-1)/2*pi} 0 0" xyz="0 0 0"/>
			</collision>
			<xacro:default_inertial mass=".05"/>
		</link>
		<joint name="${prefix}_tip_joint" type="fixed">
			<parent link="${prefix}_gripper"/>
			<child link="${prefix}_tip"/>
		</joint>
		<link name="${prefix}_tip">
			<visual>
     				<origin rpy="${(reflect-1)/2*pi} 0 0" xyz="0.09137 0.00495 0"/>
				<geometry>
					<mesh filename="package://pr2_description/meshes/gripper_v0/l_finger_tip.dae"/>
				</geometry>
			</visual>
			<collision>
				<geometry>
					<mesh filename="package://pr2_description/meshes/gripper_v0/l_finger_tip.dae"/>
				</geometry>
     				<origin rpy="${(reflect-1)/2*pi} 0 0" xyz="0.09137 0.00495 0"/>
			</collision>
			<xacro:default_inertial mass=".05"/>
		</link>
	</xacro:macro>
	<xacro:gripper prefix="left" reflect="1" />
	<xacro:gripper prefix="right" reflect="-1" />

	<link name="head">
		<visual>
			<geometry>
				<sphere radius="${width}"/>
			</geometry>
			<material name="white"/>
		</visual>
		<collision>
			<geometry>
				<sphere radius="${width}"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="10"/>
	</link>

	<joint name="head_swivel" type="continuous">
		<parent link="base_link"/>
		<child link="head"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 ${bodylen/2}"/>
	</joint>

	<link name="box">
		<visual>
			<geometry>
				<box size=".08 .08 .08"/>
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<geometry>
				<box size=".08 .08 .08"/>
			</geometry>
		</collision>
		<xacro:default_inertial mass="1"/>
	</link>
	
	<joint name="tobox" type="fixed">
		<parent link="head"/>
		<child link="box"/>
		<origin xyz="0 ${.707*width} ${.707*width}"/>
	</joint>


<!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
           <mesh filename="package://r2d2_description/meshes/hokuyo.dae" scale="1 1 1"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

<joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 0.22 0.05" rpy="0 0 1.570796"/>
    <parent link="head"/>
    <child link="hokuyo_link"/>
  </joint>


  <gazebo reference="hokuyo_link">
    <sensor type="ray" name="laser">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-2.26889</min_angle>
            <max_angle>2.2689</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>-->
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>   
     <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">-
    <!--<plugin name="laser_back" filename="libgazebo_ros_laser.so">-->

        <topicName>/base_scan</topicName>
        <frameName>hokuyo_link</frameName>
      </plugin> 
    </sensor>
  </gazebo>

 
 

</robot>
